using System.Text;
using UE5DumpUI.Models;

namespace UE5DumpUI.Services;

/// <summary>
/// Generates CE Lua invoke scripts for UFunction calls.
/// Supports two invocation paths:
///   1. DLL exports (UE5_FindInstanceOfClass, UE5_CallProcessEvent) -- works with Proxy DLL
///   2. CE built-in UE support (UseUE, UE_InvokeActorEvent) -- fallback
///
/// IMPORTANT: All Lua string literals use single quotes ('...') to avoid
/// JSON double-quote escaping issues when transmitted via the AOBMaker pipe.
/// Line endings are normalized to LF-only (\n) for CE compatibility.
/// </summary>
public static class InvokeScriptGenerator
{
    /// <summary>
    /// Generate a complete CE AA script that invokes a UFunction.
    /// </summary>
    public static string Generate(string className, string funcName, FunctionInfoModel func)
    {
        var sb = new StringBuilder(8192);
        var inputParams = func.Params.Where(p => !p.IsReturn).ToList();
        var hasParams = inputParams.Count > 0;

        Line(sb, "[ENABLE]");
        Line(sb, "{$lua}");
        Line(sb, "if syntaxcheck then return end");
        Line(sb, "-- ================================================================");
        Line(sb, $"-- UFunction Invoker: {className}::{funcName}");
        Line(sb, "-- Generated by UE5CEDumper -- resolves by name, survives restarts");
        Line(sb, "-- ================================================================");
        Line(sb);

        // Constants
        Line(sb, $"local OWNER_CLASS  = '{EscapeLua(className)}'");
        Line(sb, $"local FUNC_NAME    = '{EscapeLua(funcName)}'");
        Line(sb, $"local PARMS_SIZE   = {func.ParmsSize}");
        Line(sb);

        // Helpers for DLL calling
        AppendHelpers(sb);

        // Method detection (DLL first, CE UE fallback)
        AppendMethodDetection(sb);

        // Instance resolver (dual-path)
        AppendInstanceResolver(sb);

        // Function resolver (dual-path)
        AppendFunctionResolver(sb);

        // Print resolved info
        Line(sb, "print(string.format('  Resolved: %s::%s', OWNER_CLASS, FUNC_NAME))");
        Line(sb, "print(string.format('  Instance: 0x%X  |  UFunction: 0x%X', instanceAddr, ufuncPtr))");
        Line(sb);

        if (hasParams)
        {
            AppendParamForm(sb, className, funcName, inputParams, func.ParmsSize);
        }
        else
        {
            AppendDirectInvoke(sb, func.ParmsSize);
        }

        Line(sb, "{$asm}");
        Line(sb, "[DISABLE]");
        Line(sb, "{$lua}");
        Line(sb, "-- nop");
        Line(sb, "{$asm}");

        return sb.ToString();
    }

    /// <summary>Append a line with LF-only ending (no CR).</summary>
    private static void Line(StringBuilder sb, string text = "")
    {
        sb.Append(text);
        sb.Append('\n');
    }

    private static void AppendHelpers(StringBuilder sb)
    {
        Line(sb, "-- DLL export helper (calls UE5Dumper.dll exports via CE)");
        Line(sb, "-- returnType 1 = int32, 4 = int64/pointer (required for 64-bit addresses)");
        Line(sb, "local function dllCall(name, ...)");
        Line(sb, "    local fn = getAddress(name)");
        Line(sb, "    if not fn or fn == 0 then return nil end");
        Line(sb, "    return executeCodeEx(1, fn, ...)");
        Line(sb, "end");
        Line(sb, "local function dllCallPtr(name, ...)");
        Line(sb, "    local fn = getAddress(name)");
        Line(sb, "    if not fn or fn == 0 then return nil end");
        Line(sb, "    return executeCodeEx(4, fn, ...)");
        Line(sb, "end");
        Line(sb, "local function cstr(s)");
        Line(sb, "    local buf = allocateMemory(#s + 1)");
        Line(sb, "    writeString(buf, s)");
        Line(sb, "    writeBytes(buf + #s, {0})  -- ensure null terminator");
        Line(sb, "    return buf");
        Line(sb, "end");
        Line(sb);
    }

    private static void AppendMethodDetection(StringBuilder sb)
    {
        Line(sb, "-- Detect available invocation method");
        Line(sb, "-- DLL exports: found if version.dll (Proxy) or UE5Dumper.dll (CE inject) is loaded");
        Line(sb, "-- CE UE: fallback via built-in UseUE / UE_IsConnected");
        Line(sb, "--");
        Line(sb, "-- Some games block CE's executeCodeEx (CreateRemoteThread-based).");
        Line(sb, "-- We test with a trivial DLL call first; if nil, fall back to CE UE tools");
        Line(sb, "-- which use debug breakpoint injection instead of remote threads.");
        Line(sb, "local USE_DLL = false");
        Line(sb, "do");
        Line(sb, "    local fn = getAddress('UE5_FindInstanceOfClass')");
        Line(sb, "    if fn and fn ~= 0 then");
        Line(sb, "        -- DLL exports found, but verify executeCodeEx actually works");
        Line(sb, "        local testAddr = getAddress('UE5_GetVersion')");
        Line(sb, "        local testResult = testAddr and testAddr ~= 0 and executeCodeEx(1, testAddr) or nil");
        Line(sb, "        if testResult ~= nil then");
        Line(sb, "            USE_DLL = true");
        Line(sb, "            print(string.format('  [Invoke] Using UE5Dumper DLL exports (UE version: %s)', tostring(testResult)))");
        Line(sb, "        else");
        Line(sb, "            print('  [Invoke] DLL exports found but executeCodeEx returns nil')");
        Line(sb, "            print('  [Invoke] Game blocks CE remote threads -- use PIPE button in DumperUI instead')");
        Line(sb, "        end");
        Line(sb, "    end");
        Line(sb, "end");
        Line(sb, "if not USE_DLL then");
        Line(sb, "    if UseUE then pcall(UseUE) end");
        Line(sb, "    if not UE_IsConnected or not UE_IsConnected() then");
        Line(sb, "        print('ERROR: No UE support available!')");
        Line(sb, "        showMessage('ERROR: No UE support available!\\nMake sure UE5Dumper.dll is loaded (Proxy DLL or CE inject)\\nor CE UE tools are enabled (UseUE).')");
        AppendCleanupTimer(sb, 2);
        Line(sb, "        return");
        Line(sb, "    end");
        Line(sb, "    print('  [Invoke] Using CE built-in UE tools')");
        Line(sb, "end");
        Line(sb);
    }

    private static void AppendInstanceResolver(StringBuilder sb)
    {
        Line(sb, "-- Find a live instance (skip CDOs)");
        Line(sb, "local instanceAddr = 0");
        Line(sb, "if USE_DLL then");

        // Auto-init: Proxy DLL may be loaded but not yet initialized
        // (GObjects/GNames scanning hasn't run).  Call UE5_Init if needed.
        // UE5_Init returns bool: true (1) = success, false (0) = failure.
        // Note: executeCodeEx was already verified in method detection phase.
        Line(sb, "    local objCount = dllCall('UE5_GetObjectCount') or 0");
        Line(sb, "    if objCount == 0 then");
        Line(sb, "        print('  [Invoke] DLL not initialized -- calling UE5_Init...')");
        Line(sb, "        local initResult = dllCall('UE5_Init')");
        Line(sb, "        if initResult and initResult ~= 0 then");
        Line(sb, "            objCount = dllCall('UE5_GetObjectCount') or 0");
        Line(sb, "            print(string.format('  [Invoke] Init OK -- GObjects count: %d', objCount))");
        Line(sb, "        else");
        Line(sb, "            print(string.format('  [Invoke] Init failed (result=%s)', tostring(initResult)))");
        Line(sb, "        end");
        Line(sb, "    end");
        Line(sb, "    print(string.format('  [Invoke] GObjects count: %d', objCount))");
        Line(sb, "    local buf = cstr(OWNER_CLASS)");
        Line(sb, "    instanceAddr = dllCallPtr('UE5_FindInstanceOfClass', buf) or 0");
        Line(sb, "    print(string.format('  [Invoke] FindInstanceOfClass -> 0x%X', instanceAddr))");
        Line(sb, "    deAlloc(buf)");
        Line(sb, "else");

        // CE UE path: iterate instances
        Line(sb, "    local instOk, instances = pcall(UE_GetAllObjectsOfClass, OWNER_CLASS)");
        Line(sb, "    if instOk and instances then");
        Line(sb, "        for _, inst in ipairs(instances) do");
        Line(sb, "            local addr = inst.obj or 0");
        Line(sb, "            local fullName = inst.name or ''");
        Line(sb, "            if addr ~= 0 and not fullName:find('Default__') then");
        Line(sb, "                instanceAddr = addr");
        Line(sb, "                break");
        Line(sb, "            end");
        Line(sb, "        end");
        Line(sb, "        if instanceAddr == 0 and #instances > 0 then");
        Line(sb, "            instanceAddr = instances[1].obj or 0");
        Line(sb, "            if instanceAddr ~= 0 then");
        Line(sb, "                print('  WARNING: Only CDO instances found for ' .. OWNER_CLASS)");
        Line(sb, "            end");
        Line(sb, "        end");
        Line(sb, "    end");

        // CE UE subclass fallback
        Line(sb, "    if instanceAddr == 0 then");
        Line(sb, "        local subOk, subs = pcall(UE_GetAllSubObjectsOfClass, OWNER_CLASS)");
        Line(sb, "        if subOk and subs then");
        Line(sb, "            for _, subAddr in ipairs(subs) do");
        Line(sb, "                local fn = ''");
        Line(sb, "                local fnOk, fnStr = pcall(UE_GetObjectFullName, subAddr)");
        Line(sb, "                if fnOk and fnStr then fn = fnStr end");
        Line(sb, "                if subAddr ~= 0 and not fn:find('Default__') then");
        Line(sb, "                    instanceAddr = subAddr");
        Line(sb, "                    break");
        Line(sb, "                end");
        Line(sb, "            end");
        Line(sb, "        end");
        Line(sb, "    end");
        Line(sb, "end");
        Line(sb);

        // Error check
        Line(sb, "if instanceAddr == 0 then");
        Line(sb, @"    print('ERROR: No instance of [' .. OWNER_CLASS .. '] found!')");
        Line(sb, @"    showMessage('ERROR: No live instance of [' .. OWNER_CLASS .. '] found!\nMake sure you are in-game.')");
        AppendCleanupTimer(sb, 1);
        Line(sb, "    return");
        Line(sb, "end");
        Line(sb);
    }

    private static void AppendFunctionResolver(StringBuilder sb)
    {
        Line(sb, "-- Find the UFunction by name");
        Line(sb, "local ufuncPtr = 0");
        Line(sb, "if USE_DLL then");
        Line(sb, "    local classAddr = dllCallPtr('UE5_GetObjectClass', instanceAddr) or 0");
        Line(sb, "    if classAddr ~= 0 then");
        Line(sb, "        local buf = cstr(FUNC_NAME)");
        Line(sb, "        ufuncPtr = dllCallPtr('UE5_FindFunctionByName', classAddr, buf) or 0");
        Line(sb, "        deAlloc(buf)");
        Line(sb, "    end");
        Line(sb, "else");

        // CE UE path
        Line(sb, "    local funcOk, funcs = pcall(UE_GetFunctionsOfObject, instanceAddr, true)");
        Line(sb, "    if funcOk and funcs then");
        Line(sb, "        for _, f in ipairs(funcs) do");
        Line(sb, "            if f.name == FUNC_NAME then");
        Line(sb, "                ufuncPtr = f.ufunction");
        Line(sb, "                break");
        Line(sb, "            end");
        Line(sb, "        end");
        Line(sb, "        if ufuncPtr == 0 then");
        Line(sb, "            local lower = FUNC_NAME:lower()");
        Line(sb, "            for _, f in ipairs(funcs) do");
        Line(sb, "                if f.name and f.name:lower() == lower then");
        Line(sb, "                    ufuncPtr = f.ufunction");
        Line(sb, "                    break");
        Line(sb, "                end");
        Line(sb, "            end");
        Line(sb, "        end");
        Line(sb, "    end");
        Line(sb, "end");
        Line(sb);

        // Error check
        Line(sb, "if ufuncPtr == 0 then");
        Line(sb, "    print(string.format('ERROR: Function [%s] not found on %s!', FUNC_NAME, OWNER_CLASS))");
        Line(sb, "    showMessage(string.format('ERROR: Function [%s] not found on %s!', FUNC_NAME, OWNER_CLASS))");
        AppendCleanupTimer(sb, 1);
        Line(sb, "    return");
        Line(sb, "end");
        Line(sb);
    }

    private static void AppendDirectInvoke(StringBuilder sb, int parmsSize)
    {
        Line(sb, "-- No parameters -- invoke directly");
        Line(sb, "if USE_DLL then");
        if (parmsSize > 0)
        {
            Line(sb, $"    local pBuf = allocateMemory({parmsSize})");
            Line(sb, "    print('  Invoking UE5_CallProcessEvent...')");
            Line(sb, "    local result = dllCall('UE5_CallProcessEvent', instanceAddr, ufuncPtr, pBuf)");
            Line(sb, "    deAlloc(pBuf)");
        }
        else
        {
            Line(sb, "    print('  Invoking UE5_CallProcessEvent...')");
            Line(sb, "    local result = dllCall('UE5_CallProcessEvent', instanceAddr, ufuncPtr, 0)");
        }
        Line(sb, "    if result == 0 then print('  INVOKED OK!')");
        Line(sb, "    else print('  INVOKE FAILED: error code ' .. tostring(result)); showMessage('INVOKE FAILED:\\nerror code ' .. tostring(result)) end");
        Line(sb, "else");
        Line(sb, "    local params = {}");
        Line(sb, "    print('  Invoking UE_InvokeActorEvent...')");
        Line(sb, "    local ok, retVal = pcall(UE_InvokeActorEvent, instanceAddr, ufuncPtr, params)");
        Line(sb, "    if not ok then");
        Line(sb, "        print('  INVOKE FAILED: ' .. tostring(retVal))");
        Line(sb, "        showMessage('INVOKE FAILED:\\n' .. tostring(retVal))");
        Line(sb, "    else");
        Line(sb, "        print('  INVOKED OK!')");
        Line(sb, "    end");
        Line(sb, "end");
        AppendCleanupTimer(sb, 0);
        Line(sb);
    }

    private static void AppendParamForm(StringBuilder sb, string className, string funcName,
        List<FunctionParamModel> inputParams, int parmsSize)
    {
        Line(sb, "-- ================================================================");
        Line(sb, "-- Build parameter input form");
        Line(sb, "-- ================================================================");
        Line(sb, $"local PARAM_COUNT = {inputParams.Count}");
        Line(sb, "local labelW = 280");
        Line(sb, "local editW = 160");
        Line(sb, "local rowH = 28");
        Line(sb, "local btnH = 50");
        Line(sb, "local yPos = 10");
        Line(sb, "local contentH = math.max(PARAM_COUNT, 1) * rowH + 20");
        Line(sb, "local formH = math.min(contentH + btnH + 50, 600)");
        Line(sb, "local formW = labelW + editW + 40");
        Line(sb);
        Line(sb, "local frm = createForm(false)");
        Line(sb, "frm.Caption = string.format('%s::%s  |  0x%X', OWNER_CLASS, FUNC_NAME, instanceAddr)");
        Line(sb, "frm.Width = formW");
        Line(sb, "frm.Height = formH");
        Line(sb, "frm.Position = poScreenCenter");
        Line(sb, "frm.BorderStyle = bsSizeable");
        Line(sb);
        Line(sb, "local edits = {}");

        // Generate labels + edit fields
        for (int i = 0; i < inputParams.Count; i++)
        {
            var p = inputParams[i];
            var label = $"{p.Name}  [{ShortTypeName(p.TypeName)}, {p.Size} B{(p.IsOut ? ", out" : "")}]";
            var defaultVal = GetDefaultValue(p.TypeName);
            int idx = i + 1;

            Line(sb, "    do");
            Line(sb, "        local lbl = createLabel(frm)");
            Line(sb, $"        lbl.Caption = '{EscapeLua(label)}'");
            Line(sb, "        lbl.Left = 10");
            Line(sb, "        lbl.Top = yPos + 2");
            Line(sb, "        lbl.AutoSize = true");
            Line(sb, "        local edt = createEdit(frm)");
            Line(sb, $"        edt.Text = '{defaultVal}'");
            Line(sb, "        edt.Left = labelW + 20");
            Line(sb, "        edt.Top = yPos");
            Line(sb, "        edt.Width = editW");
            Line(sb, $"        edits[{idx}] = edt");
            Line(sb, "        yPos = yPos + rowH");
            Line(sb, "    end");
        }

        // Buttons
        Line(sb);
        Line(sb, "local btnY = formH - btnH - 10");
        Line(sb, "local btnFire = createButton(frm)");
        Line(sb, "btnFire.Caption = 'FIRE'");
        Line(sb, "btnFire.Width = 120");
        Line(sb, "btnFire.Height = 34");
        Line(sb, "btnFire.Left = 10");
        Line(sb, "btnFire.Top = btnY");
        Line(sb);
        Line(sb, "local btnCancel = createButton(frm)");
        Line(sb, "btnCancel.Caption = 'Cancel'");
        Line(sb, "btnCancel.Width = 90");
        Line(sb, "btnCancel.Height = 34");
        Line(sb, "btnCancel.Left = 140");
        Line(sb, "btnCancel.Top = btnY");
        Line(sb, "btnCancel.OnClick = function() frm.close() end");
        Line(sb);

        // On close: deactivate memrec
        Line(sb, "frm.OnClose = function(sender)");
        AppendCleanupTimer(sb, 1);
        Line(sb, "    return caFree");
        Line(sb, "end");
        Line(sb);

        // Fire button logic (dual-path)
        Line(sb, "btnFire.OnClick = function()");
        Line(sb, "    if USE_DLL then");

        // DLL path: allocate param buffer, write values, call ProcessEvent
        Line(sb, $"        local pBuf = allocateMemory({parmsSize})");
        // Zero-fill
        Line(sb, $"        local zeros = {{}}");
        Line(sb, $"        for i = 1, {parmsSize} do zeros[i] = 0 end");
        Line(sb, "        writeBytes(pBuf, zeros)");

        // Write each param to the buffer at its offset
        for (int i = 0; i < inputParams.Count; i++)
        {
            var p = inputParams[i];
            int idx = i + 1;
            var parseExpr = GetParseExpression(p.TypeName, idx);
            var writeStmt = GetCeWriteStatement(p.TypeName, p.Size, p.Offset, parseExpr);
            Line(sb, $"        {writeStmt}");
        }

        Line(sb, "        print('  Invoking UE5_CallProcessEvent...')");
        Line(sb, "        local result = dllCall('UE5_CallProcessEvent', instanceAddr, ufuncPtr, pBuf)");
        Line(sb, "        deAlloc(pBuf)");
        Line(sb, "        if result == 0 then print('  INVOKED OK!')");
        Line(sb, "        else print('  INVOKE FAILED: error code ' .. tostring(result)); showMessage('INVOKE FAILED:\\nerror code ' .. tostring(result)) end");

        Line(sb, "    else");

        // CE UE path: build params table
        Line(sb, "        local params = {}");
        for (int i = 0; i < inputParams.Count; i++)
        {
            var p = inputParams[i];
            var ceType = GetCeSizeType(p.TypeName, p.Size);
            int idx = i + 1;
            var parseExpr = GetParseExpression(p.TypeName, idx);
            Line(sb, $"        table.insert(params, {{type={ceType}, value={parseExpr}}})");
        }
        Line(sb, "        print(string.format('  Invoking UE_InvokeActorEvent with %d params...', #params))");
        Line(sb, "        local ok, retVal = pcall(UE_InvokeActorEvent, instanceAddr, ufuncPtr, params)");
        Line(sb, "        if not ok then");
        Line(sb, "            print('  INVOKE FAILED: ' .. tostring(retVal))");
        Line(sb, "            showMessage('INVOKE FAILED:\\n' .. tostring(retVal))");
        Line(sb, "        else");
        Line(sb, "            print('  INVOKED OK!')");
        Line(sb, "        end");

        Line(sb, "    end");
        Line(sb, "    frm.close()");
        Line(sb, "end");
        Line(sb);
        Line(sb, "frm.show()");
        Line(sb);
    }

    private static void AppendCleanupTimer(StringBuilder sb, int indent)
    {
        var pad = new string(' ', indent * 4);
        Line(sb, $"{pad}local t = createTimer(nil, false)");
        Line(sb, $"{pad}t.Interval = 100");
        Line(sb, $"{pad}t.OnTimer = function(s) s.Enabled = false; s.destroy(); if memrec then memrec.Active = false end end");
        Line(sb, $"{pad}t.Enabled = true");
    }

    /// <summary>Generate a CE Lua write statement for a param in the ProcessEvent buffer.</summary>
    private static string GetCeWriteStatement(string typeName, int size, int offset, string valueExpr)
    {
        string writeFunc = typeName switch
        {
            "BoolProperty" or "ByteProperty" or "Int8Property"
                => "writeBytes",
            "Int16Property" or "UInt16Property"
                => "writeSmallInteger",
            "FloatProperty"
                => "writeFloat",
            "DoubleProperty"
                => "writeDouble",
            "Int64Property" or "UInt64Property"
                or "NameProperty" or "ObjectProperty" or "ClassProperty"
                or "SoftObjectProperty" or "WeakObjectProperty"
                or "LazyObjectProperty" or "InterfaceProperty"
                => "writeQword",
            "IntProperty" or "UInt32Property" or "EnumProperty"
                => "writeInteger",
            _ => size switch
            {
                1 => "writeBytes",
                2 => "writeSmallInteger",
                8 => "writeQword",
                _ => "writeInteger",
            },
        };

        // writeBytes takes a table: writeBytes(addr, {val})
        if (writeFunc == "writeBytes")
            return $"writeBytes(pBuf + {offset}, {{{valueExpr}}})";

        return $"{writeFunc}(pBuf + {offset}, {valueExpr})";
    }

    /// <summary>Map UE property type to CE size constant.</summary>
    private static string GetCeSizeType(string typeName, int size)
    {
        return typeName switch
        {
            "BoolProperty" => "szByte",
            "ByteProperty" or "Int8Property" => "szByte",
            "Int16Property" or "UInt16Property" => "szWord",
            "IntProperty" or "UInt32Property" or "EnumProperty" => "szDword",
            "Int64Property" or "UInt64Property" => "szQword",
            "FloatProperty" => "szFloat",
            "DoubleProperty" => "szDouble",
            "NameProperty" or "ObjectProperty" or "ClassProperty"
                or "SoftObjectProperty" or "WeakObjectProperty"
                or "LazyObjectProperty" or "InterfaceProperty" => "szQword",
            _ => size switch
            {
                1 => "szByte",
                2 => "szWord",
                4 => "szDword",
                8 => "szQword",
                _ => "szDword",
            },
        };
    }

    /// <summary>Short display name for param type label.</summary>
    private static string ShortTypeName(string typeName)
    {
        return typeName switch
        {
            "BoolProperty" => "bool",
            "ByteProperty" => "uint8",
            "Int8Property" => "int8",
            "Int16Property" => "int16",
            "UInt16Property" => "uint16",
            "IntProperty" => "int32",
            "UInt32Property" => "uint32",
            "Int64Property" => "int64",
            "UInt64Property" => "uint64",
            "FloatProperty" => "float",
            "DoubleProperty" => "double",
            "NameProperty" => "FName",
            "ObjectProperty" => "UObject*",
            "ClassProperty" => "UClass*",
            "StrProperty" => "FString",
            "TextProperty" => "FText",
            "EnumProperty" => "enum",
            "StructProperty" => "struct",
            _ => typeName.Replace("Property", ""),
        };
    }

    /// <summary>Default edit field value for a type.</summary>
    private static string GetDefaultValue(string typeName)
    {
        return typeName switch
        {
            "FloatProperty" or "DoubleProperty" => "0.0",
            "BoolProperty" => "0",
            "NameProperty" or "ObjectProperty" or "ClassProperty"
                or "SoftObjectProperty" or "WeakObjectProperty"
                or "InterfaceProperty" => "0x0",
            _ => "0",
        };
    }

    /// <summary>Lua expression to parse edit field text into a numeric value.</summary>
    private static string GetParseExpression(string typeName, int editIndex)
    {
        // Pointer/FName types: hex-aware parsing
        if (typeName is "NameProperty" or "ObjectProperty" or "ClassProperty"
            or "SoftObjectProperty" or "WeakObjectProperty" or "InterfaceProperty")
        {
            return $"(function() local s = edits[{editIndex}].Text; " +
                   "if s:sub(1,2) == '0x' or s:sub(1,2) == '0X' then " +
                   "return tonumber(s, 16) or 0 else return tonumber(s) or 0 end end)()";
        }

        // Float types: direct tonumber
        if (typeName is "FloatProperty" or "DoubleProperty")
            return $"tonumber(edits[{editIndex}].Text) or 0.0";

        // Integer types: floor to avoid fractional
        return $"math.floor(tonumber(edits[{editIndex}].Text) or 0)";
    }

    /// <summary>Escape special characters for Lua single-quoted string literal.</summary>
    private static string EscapeLua(string s)
    {
        return s.Replace("\\", "\\\\").Replace("'", "\\'").Replace("\n", "\\n");
    }
}
