using System.Text;
using System.Text.Json.Nodes;
using UE5DumpUI.Core;
using UE5DumpUI.Models;

namespace UE5DumpUI.Services;

/// <summary>
/// Generates symbol maps / label databases for debuggers.
/// Supported formats: x64dbg (.dd64 JSON), Ghidra (text), IDA (.idc script).
/// </summary>
public static class SymbolExportService
{
    /// <summary>
    /// Collect all objects from the DLL via paginated get_object_list,
    /// transforming each into a <see cref="SymbolEntry"/> with module-relative address.
    /// </summary>
    public static async Task<List<SymbolEntry>> CollectSymbolsAsync(
        IDumpService dump, string moduleName, string moduleBase,
        IProgress<string>? progress = null, CancellationToken ct = default)
    {
        if (!ulong.TryParse(moduleBase.Replace("0x", "").Replace("0X", ""),
                System.Globalization.NumberStyles.HexNumber, null, out var modBase))
            modBase = 0;

        var symbols = new List<SymbolEntry>();
        int offset = 0;
        const int pageSize = 5000;
        int total = 0;

        do
        {
            ct.ThrowIfCancellationRequested();
            var page = await dump.GetObjectListAsync(offset, pageSize, ct);
            total = page.Total;

            foreach (var obj in page.Objects)
            {
                if (string.IsNullOrEmpty(obj.Address) || string.IsNullOrEmpty(obj.Name))
                    continue;

                if (!ulong.TryParse(obj.Address.Replace("0x", "").Replace("0X", ""),
                        System.Globalization.NumberStyles.HexNumber, null, out var addr))
                    continue;

                var relAddr = modBase > 0 ? addr - modBase : addr;

                // Determine category from class name
                var category = CategorizeObject(obj.ClassName);

                // Build a clean label name (replace invalid chars)
                var label = SanitizeLabel(obj.Name);

                symbols.Add(new SymbolEntry
                {
                    Address = $"0x{addr:X}",
                    ModuleRelative = $"0x{relAddr:X}",
                    Name = label,
                    ClassName = obj.ClassName,
                    Category = category,
                });
            }

            offset += page.Scanned > 0 ? page.Scanned : page.Objects.Count;
            progress?.Report($"Collecting symbols... ({symbols.Count} / {total})");
        } while (offset < total);

        progress?.Report($"Collected {symbols.Count} symbols");
        return symbols;
    }

    /// <summary>
    /// Generate x64dbg database JSON (.dd64) with module-relative labels.
    /// </summary>
    public static string GenerateX64dbgDatabase(
        IReadOnlyList<SymbolEntry> symbols, string moduleName)
    {
        // x64dbg .dd64 format: JSON with "labels" and optional "comments" arrays.
        // Addresses are module-relative hex strings (no "0x" prefix).
        var labels = new JsonArray();
        var comments = new JsonArray();

        foreach (var sym in symbols)
        {
            var relHex = sym.ModuleRelative.Replace("0x", "").Replace("0X", "");
            labels.Add(new JsonObject
            {
                ["module"] = moduleName,
                ["address"] = relHex,
                ["manual"] = true,
                ["text"] = sym.Name,
            });

            // Add class name as comment for non-generic objects
            if (!string.IsNullOrEmpty(sym.ClassName) && sym.Category != "Object")
            {
                comments.Add(new JsonObject
                {
                    ["module"] = moduleName,
                    ["address"] = relHex,
                    ["manual"] = true,
                    ["text"] = sym.ClassName,
                });
            }
        }

        var root = new JsonObject
        {
            ["labels"] = labels,
            ["comments"] = comments,
        };

        return root.ToJsonString(new System.Text.Json.JsonSerializerOptions { WriteIndented = true });
    }

    /// <summary>
    /// Generate Ghidra symbol text file (label + absolute address, one per line).
    /// Compatible with Ghidra's ImportSymbolsScript.py.
    /// </summary>
    public static string GenerateGhidraSymbols(IReadOnlyList<SymbolEntry> symbols)
    {
        // Format: "label address [type]" per line
        // Example: "AActor 0x7FF612340000 f"
        var sb = new StringBuilder(symbols.Count * 60);
        sb.AppendLine("// Generated by UE5CEDumper — Ghidra Symbol Import");
        sb.AppendLine("// Import via: File → Parse C Source or ImportSymbolsScript.py");

        foreach (var sym in symbols)
        {
            // Ghidra format: NAME ADDRESS TYPE
            // Type: 'f' for function, 'l' for label
            var type = sym.Category == "Function" ? "f" : "l";
            sb.Append(sym.Name);
            sb.Append(' ');
            sb.Append(sym.Address);
            sb.Append(' ');
            sb.AppendLine(type);
        }

        return sb.ToString();
    }

    /// <summary>
    /// Generate IDA .idc script with MakeName / MakeComm calls.
    /// </summary>
    public static string GenerateIdaScript(IReadOnlyList<SymbolEntry> symbols)
    {
        var sb = new StringBuilder(symbols.Count * 80);
        sb.AppendLine("#include <idc.idc>");
        sb.AppendLine();
        sb.AppendLine("// Generated by UE5CEDumper — IDA Symbol Import");
        sb.AppendLine("static main() {");

        foreach (var sym in symbols)
        {
            var addr = sym.Address;
            var escapedName = EscapeIdcString(sym.Name);
            sb.Append("    MakeName(");
            sb.Append(addr);
            sb.Append(", \"");
            sb.Append(escapedName);
            sb.AppendLine("\");");

            if (!string.IsNullOrEmpty(sym.ClassName) && sym.Category != "Object")
            {
                var escapedClass = EscapeIdcString(sym.ClassName);
                sb.Append("    MakeComm(");
                sb.Append(addr);
                sb.Append(", \"");
                sb.Append(escapedClass);
                sb.AppendLine("\");");
            }
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    // --- Helpers ---

    private static string CategorizeObject(string className)
    {
        return className switch
        {
            "Class" => "Class",
            "ScriptStruct" => "Struct",
            "Enum" => "Enum",
            "Function" => "Function",
            _ => "Object",
        };
    }

    /// <summary>
    /// Sanitize a UObject name to a valid label for debuggers.
    /// Replace spaces, slashes, and special chars with underscores.
    /// </summary>
    internal static string SanitizeLabel(string name)
    {
        if (string.IsNullOrEmpty(name)) return "unknown";

        var sb = new StringBuilder(name.Length);
        foreach (var c in name)
        {
            if (char.IsLetterOrDigit(c) || c == '_' || c == '.')
                sb.Append(c);
            else
                sb.Append('_');
        }
        return sb.Length == 0 ? "unknown" : sb.ToString();
    }

    private static string EscapeIdcString(string s)
    {
        return s.Replace("\\", "\\\\").Replace("\"", "\\\"");
    }
}
